### ISSUE TITLE
`curl::curl_download()` does not play nicely with certain networks; revert to `utils::download.file()`

### ISSUE THREAD

**Issue by ch3lle82** [MattCowgill/readabs#133] opened 2021-03-30 01:10 UTC
Hi Matt

We use the read_abs() function, which imports data directly from the ABS website, quite regularly as part of our work. The functionality still works for me on the work network as I'm currently using the older version of R (3.6.1) and therefore the older readabs package. However, the read_abs() function no longer works for several of my colleagues who have upgraded to the latest R version (4.0.4) and were therefore required to download the latest readabs package. 

We have already spoken to our internal IT department who advised us that there is nothing they can do. Just wondering whether this is an issue that has been raised by other users who use your package at work? And is it something you'd be able to assist with, or work with our IT department to fix? It appears that our IT security network is blocking access to the ABS website when using the new readabs package, but not under the old one. I have attached a screenshot of the error msg for reference.

Kind [regards](url
![Readabs error message](https://user-images.githubusercontent.com/65281019/112918575-e62c3480-9150-11eb-8108-ad6c87233745.PNG)
)
Michelle

**Comment by MattCowgill** [comment] 2021-03-30 02:04
Hi @ch3lle82, sorry you've encountered problems. No, the problem you describe has not been reported by other users.

It is difficult for me to diagnose the cause of this issue, as I obviously cannot reproduce your IT environment. `readabs::read_abs()` works fine on R 4.0.4 in general - that is the version I have installed locally, and the package is tested with R 4.0.4 on GitHub Actions.  

Can you please ask your colleagues to run the following function: 

```
readabs:::check_abs_connection()
```
If readabs can contact the ABS server, nothing will be returned. If it cannot contact the ABS, an error will be returned. In this case, please post the error message they encounter. 

If that works, please ask them to run the following code: 

```
url <- "https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/weekly-payroll-jobs-and-wages-australia/week-ending-13-march-2021/6160055001_DO001.xlsx"

file_1 <- tempfile(fileext = ".xlsx")
download.file(url, file_1)
readxl::read_excel(file_1)

file_2 <- tempfile(fileext = ".xlsx")
curl::curl_download(url, file_2)
readxl::read_excel(file_2)
```

Please report any errors they encounter.

Also please get them to run this code and report any errors: 
```
xml_url <- readabs:::form_abs_tsd_url("6345.0", "1") 
readabs:::get_abs_xml_metadata(xml_url)
```

**Comment by ch3lle82** [comment] 2021-03-30 03:06
Hi Matt

Thanks for your quick response! My colleague has tested the codes provided and encountered the following errors:

readxl::read_excel(file_1)
Error: Evaluation error: error -103 with zipfile in unzGetCurrentFileInfo

curl::curl_download(url, file_2)
Error in curl::curl_download(url, file_2) : 
  Failed to connect to www.abs.gov.au port 443: Timed out
readxl::read_excel(file_2)
Error: `path` does not exist: ‘C:\Users\lv2647\AppData\Local\Temp\1\RtmpSQMRL8\file2ba8335132d3.xlsx’

readabs:::get_abs_xml_metadata(xml_url)
Error in open.connection(x, "rb") : 
  Failed to connect to ausstats.abs.gov.au port 443: Timed out

**Comment by HughParsonage** [comment] 2021-03-30 03:35
Another long-shot would be to mask the HTTP user agent by running

```r
options(HTTPUserAgent = "")
```
before retrying.

**Comment by MattCowgill** [comment] 2021-03-30 03:36
@ch3lle82 Thank you. 

Can I confirm: was any error encountered with this code block: 

```
file_1 <- tempfile(fileext = ".xlsx")
download.file(url, file_1)
```

**Comment by ch3lle82** [comment] 2021-03-30 03:37
Hi Matt, no error was encountered when running the code block:
file_1 <- tempfile(fileext = ".xlsx")
download.file(url, file_1)

**Comment by MattCowgill** [comment] 2021-03-30 03:40
OK thanks @ch3lle82. 

So if they run this block, an error is only encountered on the third line? 

```
file_1 <- tempfile(fileext = ".xlsx")
download.file(url, file_1)
readxl::read_excel(file_1)
```

**Comment by ch3lle82** [comment] 2021-03-30 03:47
Hi Matt, yes that's correct.

**Comment by HughParsonage** [comment] 2021-03-30 03:48
Can you try this? (Note the wb)

```r
url <- "https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/weekly-payroll-jobs-and-wages-australia/week-ending-13-march-2021/6160055001_DO001.xlsx"
file_1 <- tempfile(fileext = ".xlsx")
download.file(url, file_1, mode = "wb")
readxl::read_excel(file_1)
```

**Comment by ch3lle82** [comment] 2021-03-30 04:01
Hi Hugh, adding the wb seems to have worked for the first block of code!

We tried to do the same for the second block of code, i.e.:
file_2 <- tempfile(fileext = ".xlsx")
curl::curl_download(url, file_2, mode = "wb")

But we still get the same error msg:
Error in curl::curl_download(url, file_2) :
Failed to connect to www.abs.gov.au port 443: Timed out

**Comment by OscarLane** [comment] 2021-03-30 05:53
Hey @MattCowgill, I get this when running `readabs::check_abs_connection()`:

```
Error in check_abs_connection() : 
  R cannot access the ABS website. `read_abs()` requires access to the ABS site. Please check your internet connection and security settings.
```

As mentioned on Slack, `download.file()` works:

```
> download.file("http://abs.gov.au/robots.txt", destfile = "~/robots.txt")
trying URL 'http://abs.gov.au/robots.txt'
Content type 'text/plain; charset=UTF-8' length 534 bytes
downloaded 534 bytes

```

**Comment by OscarLane** [comment] 2021-03-30 05:54
Using curl gets me nowhere :(

```
> curl::curl_download("http://abs.gov.au/robots.txt", destfile = "~/robots.txt")
Error in curl::curl_download("http://abs.gov.au/robots.txt", destfile = "~/robots.txt") : 
  Could not resolve host: abs.gov.au
```

**Comment by MattCowgill** [comment] 2021-03-30 22:16
OK, in the coming days I will update `{readabs}` so that it uses `utils::download.file()` rather than `curl::curl_download()`. I hope this will fix at least some of these problems

**Comment by MattCowgill** [comment] 2021-04-04 06:56
@ch3lle82 I have updated `readabs` to change the way files are downloaded.

If your colleagues are able to install packages from GitHub, please ask them to update using this code:

```
if (!require(remotes)) install.packages("remotes")
remotes::install_github("mattcowgill/readabs")
```

Then ask them to try `readabs::read_abs()` again after restarting their R session. I'd appreciate any feedback you can give about their success or otherwise.

**Comment by ch3lle82** [comment] 2021-04-06 01:53
Hi Matt, thanks for amending the package so quickly! Unfortunately my colleague ran that block of code you provided and encountered an error. I think our IT network may be blocking the installation of packages from GitHub through R Studio. This is the error he receives after running the second line:

Error: Failed to install 'readabs' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds

**Comment by OscarLane** [comment] 2021-04-06 02:15
@ch3lle82: you may be able to install the package by going to the `readabs` github page, pressing Code -> Download ZIP, then opening `readabs.Rproj` and building the package. May or may not require require rtools installed if you're on Windows though.

**Comment by OscarLane** [comment] 2021-04-12 03:00
Hi @MattCowgill,

On my network, by default this doesn't work but I can get `check_abs_connection()` to work by setting proxy settings for httr. The problem then becomes 

```
> read_abs(cat_no = "6202.0")
Finding filenames for tables corresponding to ABS catalogue 6202.0
 Error in open.connection(x, "rb") : 
  Could not resolve host: ausstats.abs.gov.au 
```

Traceback if helpful:

**Comment by OscarLane** [comment] 2021-04-12 03:07
Wonder if it could be that xml2 is using curl under the hood?

```
> library(xml2)
> xml2::read_xml("https://www.w3schools.com/xml/note.xml")
Error in open.connection(x, "rb") : 
  Could not resolve host: www.w3schools.com
```

**Comment by OscarLane** [comment] 2021-04-12 03:10
Might be the case: appears to work when I do

```
> httr::GET("https://www.w3schools.com/xml/note.xml") %>%
+   httr::content("text") %>%
+   xml2::read_xml()
No encoding supplied: defaulting to UTF-8.
{xml_document}
<note>
[1] <to>Tove</to>
[2] <from>Jani</from>
[3] <heading>Reminder</heading>
[4] <body>Don't forget me this weekend!</body>
```

**Comment by MattCowgill** [comment] 2021-04-12 03:27
Thanks @OscarLane - I think that's it. I'll aim to fix this up this week.

**Comment by MattCowgill** [comment] 2021-04-16 04:52
Hi @OscarLane I've tried to fix this issue. Work in progress in the `eliminate-residual-curl` branch. 

If you're able, it'd be great if you can test it out. Install with `devtools::install_github("mattcowgill/readabs", "eliminate-residual-curl")`.

**Comment by OscarLane** [comment] 2021-04-17 00:53
Eureka! It works! And extra cool because it seems I don't even have to set the `httr` proxy settings myself

**Comment by MattCowgill** [comment] 2021-04-17 02:41
Yaaaay! Thanks @OscarLane. Is it noticeably slow?

**Comment by MattCowgill** [comment] 2021-04-17 03:46
Merged that branch into `master` now.

**Closed by MattCowgill** 2021-04-17 03:46 UTC

**Comment by OscarLane** [comment] 2021-04-17 04:04
Thanks for all your efforts @MattCowgill! And it was a bit slow when I tried, but possibly because I'm at home and connecting through a VPN which is slow at the best of times. Have you noticed much difference?

**Comment by MattCowgill** [comment] 2021-04-17 04:26
A little, yeah. It's still acceptably fast, but I'll try to speed things up. See the linked issue above for one of the pain points - downloading an XML file and then reading from disk is about ~half the speed of reading the XML file direciton from a URL

**Comment by MattCowgill** [comment] 2021-05-24 04:33
FYI all - I have submitted version 0.4.9 to CRAN (which is the current GitHub version). This should - I hope - play nicer with networks that block `curl`.
