### ISSUE TITLE
Error `cannot coerce type 'closure' to vector of type 'character'` due to ABS website issue

### ISSUE THREAD

**Issue by ZacMuscat** [MattCowgill/readabs#242] opened 2023-12-10 03:02 UTC
I have been using the read abs package for sometime, thank you for your contribution.

Today (10 Dec 23) i tried running one of my scripts which i have been using weekly for the past 18-months. The specific function is:

DATA <- read_abs(series_id = "A2304372W")

The above function no longer imported the specified series but gave me the error:

Finding URLs for tables corresponding to ABS series IDA2304372W
Attempting to download files from series IDA2304372W, Australian National Accounts: National Income, Expenditure and Product
trying URL 'https://www.abs.gov.au/statistics/economy/national-accounts/australian-national-accounts-national-income-expenditure-and-product/latest-release/5206001_key_aggregates.xlsx'
trying URL 'https://www.abs.gov.au/statistics/economy/national-accounts/australian-national-accounts-national-income-expenditure-and-product/latest-release/5206001_key_aggregates.xls'
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'

I tried running this script on two different computers, and i tried re-installing the read.abs package as well but not luck. Hopefully this is an easy fix.

**Comment by MattCowgill** [comment] 2023-12-10 04:07
Hi @ZacMuscat 
I got an email from the ABS late on Friday notifying me of a problem with the ABS Time Series Directory that will affect readabs users. I believe this is the cause of your issue. The ABS assures me this will be fixed ASAP. It’s not an issue with the package itself and isn’t something I can remedy. Sorry for the inconvenience. 

Matt

**Comment by MattCowgill** [comment] 2023-12-10 04:24
@ZacMuscat I’m on my laptop right now. Later this evening I’ll see if I can write some code that works around the ABS issue.

**Comment by MattCowgill** [comment] 2023-12-10 21:51
@ZacMuscat

The ABS problem is related to fetching the "latest issue" data without specifying the release date. 
While we wait for the ABS to resolve this (I hope today), you can fetch the data by specifying the release date, as in:

```
read_abs(series_id = "A2304372W",
         release_date = "2023-09-01")
```

Or in your case @jasemurphy, 

```
read_abs("5601.0", release_date = "2022-10-01")
```

Note that the 'release date' should be the 'reference period' for the data, as in the examples above. 

I'll update this thread when the ABS notifies me the problem has been resolved.

**Comment by ZacMuscat** [comment] 2023-12-10 22:01
Good morning,

Thank you for the update, much appreciated.

Zac Muscat

**Comment by Wade008** [comment] 2023-12-10 23:06
> @ZacMuscat
> 
> The ABS problem is related to fetching the "latest issue" data without specifying the release date. While we wait for the ABS to resolve this (I hope today), you can fetch the data by specifying the release date, as in:
> 
> ```
> read_abs(series_id = "A2304372W",
>          release_date = "2023-09-01")
> ```
> 
> Or in your case @jasemurphy,
> 
> ```
> read_abs("5601.0", release_date = "2022-10-01")
> ```
> 
> Note that the 'release date' should be the 'reference period' for the data, as in the examples above.
> 
> I'll update this thread when the ABS notifies me the problem has been resolved.

Thanks for following up on this and for providing a work around.

**Comment by MattCowgill** [comment] 2023-12-11 09:04
Hi, I have been informed by the ABS that they've resolved the issue on their side. I've confirmed that `readabs::read_abs()` now works again, with no update to the package or modifications to your code required.

@jasemurphy @Wade008 @ZacMuscat

**Closed by MattCowgill** 2023-12-11 09:04 UTC

**Comment by HughParsonage** [comment] 2023-12-11 09:33
Looks to be a nontrivial change: https://github.com/HughParsonage/ABS-Catalogue/commit/18cd6348862f56990e4ded2d799e04ed186722b4

**Comment by MattCowgill** [comment] 2023-12-11 10:00
Is that showing revisions to actual data @HughParsonage?

**Comment by Wade008** [comment] 2023-12-11 10:12
> Hi, I have been informed by the ABS that they've resolved the issue on their side. I've confirmed that `readabs::read_abs()` now works again, with no update to the package or modifications to your code required.
> 
> @jasemurphy @Wade008 @ZacMuscat 

Thanks again Matt.

**Comment by HughParsonage** [comment] 2023-12-11 10:33
@MattCowgill Yes
